#!/usr/bin/env php
<?php

/**
 * helper – DevelopmentHelper
 *
 * Copyright (C) 2015-2017 Jack Noordhuis
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * @author Jack Noordhuis
 *
 */

define("HELPER_START", microtime(true));

require __DIR__ . "/vendor/autoload.php"; // composer autoload files

new helper\HelperApplication; // run the application